import  DashboardHead  from "@/components/ui/DashboardHead";
import type { Metadata } from "next";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Dashboardlayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <div>
    <DashboardHead />
    {children}
   </div>
  );
}
